//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public int CellID { get; set; }
        public int SectorID { get; set; }
        public int CellX { get; set; }
        public int CellY { get; set; }
        public bool HasNorthWall { get; set; }
        public bool HasWestWall { get; set; }
        public bool HasSouthWall { get; set; }
        public bool HasEastWall { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
