//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defense
    {
        public int DefenseID { get; set; }
        public int DefenseSetID { get; set; }
        public int Rank { get; set; }
        public int DiceCount { get; set; }
        public string DiceColor { get; set; }
    
        public virtual DefenseSet DefenseSet { get; set; }
    }
}
