//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefenseSet
    {
        public DefenseSet()
        {
            this.Defenses = new HashSet<Defense>();
            this.Units = new HashSet<Unit>();
        }
    
        public int DefenseSetID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Defense> Defenses { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
