//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int EntranceID { get; set; }
        public int SectorID { get; set; }
        public string Name { get; set; }
        public int Cell1X { get; set; }
        public int Cell1Y { get; set; }
        public int Cell2X { get; set; }
        public int Cell2Y { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
