//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraActionsSet
    {
        public ExtraActionsSet()
        {
            this.Corporations = new HashSet<Corporation>();
            this.ExtraActions = new HashSet<ExtraAction>();
        }
    
        public int ExtraActionsSetID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Corporation> Corporations { get; set; }
        public virtual ICollection<ExtraAction> ExtraActions { get; set; }
    }
}
