//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSetMapping
    {
        public int ItemSetMappingID { get; set; }
        public int ItemID { get; set; }
        public int ItemSetID { get; set; }
    
        public virtual ItemSet ItemSet { get; set; }
        public virtual Item Item { get; set; }
    }
}
