//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemStats = new HashSet<ItemStat>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> ItemSetID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Cost { get; set; }
        public Nullable<int> RankRequired { get; set; }
        public string ImgShopPath { get; set; }
        public string ImgIconPath { get; set; }
        public string ImgLargePath { get; set; }
        public string ImgAlternatePath { get; set; }
        public string CorporationRequired { get; set; }
        public bool IsSoldInShop { get; set; }
    
        public virtual ItemSet ItemSet { get; set; }
        public virtual ICollection<ItemStat> ItemStats { get; set; }
    }
}
