//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStat
    {
        public int ItemStatID { get; set; }
        public int ItemID { get; set; }
        public string StatType { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> DiceCount { get; set; }
        public Nullable<int> DiceReroll { get; set; }
        public string DiceColor { get; set; }
        public Nullable<int> ArmorPenetration { get; set; }
        public string Special { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
