//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCGameDataEntities : DbContext
    {
        public MCGameDataEntities()
            : base("name=MCGameDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cell> Cells { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<ArmorSet> ArmorSets { get; set; }
        public virtual DbSet<Corporation> Corporations { get; set; }
        public virtual DbSet<Defense> Defenses { get; set; }
        public virtual DbSet<DefenseSet> DefenseSets { get; set; }
        public virtual DbSet<ItemSet> ItemSets { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemStat> ItemStats { get; set; }
        public virtual DbSet<Entrance> Entrances { get; set; }
        public virtual DbSet<SectorMap> SectorMaps { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
    }
}
