//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public Mission()
        {
            this.SectorMaps = new HashSet<SectorMap>();
            this.Objectives = new HashSet<Objective>();
        }
    
        public int MissionID { get; set; }
        public string MissionNumber { get; set; }
        public string Name { get; set; }
        public string TextBriefing { get; set; }
        public string TextDescription { get; set; }
        public string TextTimeLimit { get; set; }
        public string TextDarkLegion { get; set; }
        public string TextRewards { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<bool> IsSecondaryMissions { get; set; }
        public string ImgMissionPath { get; set; }
        public string ImgMapPath { get; set; }
        public Nullable<int> RewardDoomtrooperCredits { get; set; }
        public Nullable<int> RewardDoomtrooperPromotionPoints { get; set; }
        public Nullable<int> RewardDoomtrooperItemID { get; set; }
        public Nullable<int> RewardLegionCredits { get; set; }
        public Nullable<int> RewardLegionPromotionPoints { get; set; }
        public Nullable<int> RewardLegionItemID { get; set; }
    
        public virtual ICollection<SectorMap> SectorMaps { get; set; }
        public virtual ICollection<Objective> Objectives { get; set; }
    }
}
