//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        public int ObjectiveID { get; set; }
        public int MissionID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TimeLimitRound { get; set; }
        public Nullable<bool> TimeLimitIsStartOfRound { get; set; }
        public Nullable<int> RequiredCount1 { get; set; }
        public Nullable<int> RequiredCount2 { get; set; }
        public Nullable<int> RequiredCount3 { get; set; }
        public string RequiredUnitType1 { get; set; }
        public string RequiredUnitType2 { get; set; }
        public string RequiredUnitType3 { get; set; }
        public Nullable<int> RequiredSectorID1 { get; set; }
        public Nullable<int> RequiredSectorID2 { get; set; }
        public Nullable<int> RequiredSectorID3 { get; set; }
        public Nullable<int> RequiredSectorID4 { get; set; }
        public Nullable<int> RequiredCellX { get; set; }
        public Nullable<int> RequiredCellY { get; set; }
        public string Special1 { get; set; }
        public string Special2 { get; set; }
        public string Special3 { get; set; }
    
        public virtual Mission Mission { get; set; }
    }
}
