//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosChronicles_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectorMap
    {
        public int SectorMapID { get; set; }
        public int MissionID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> LocationX { get; set; }
        public Nullable<int> LocationY { get; set; }
        public Nullable<bool> IsEntranceTBlocked { get; set; }
        public Nullable<bool> IsEntranceTForDoomtroopers { get; set; }
        public Nullable<bool> IsEntranceTForLegion { get; set; }
        public Nullable<bool> IsEntranceRBlocked { get; set; }
        public Nullable<bool> IsEntranceRForDoomtroopers { get; set; }
        public Nullable<bool> IsEntranceRForLegion { get; set; }
        public Nullable<bool> IsEntranceBBlocked { get; set; }
        public Nullable<bool> IsEntranceBForDoomtroopers { get; set; }
        public Nullable<bool> IsEntranceBForLegion { get; set; }
        public Nullable<bool> IsEntranceLBlocked { get; set; }
        public Nullable<bool> IsEntranceLForDoomtroopers { get; set; }
        public Nullable<bool> IsEntranceLForLegion { get; set; }
    
        public virtual Mission Mission { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
