BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ItemStat
	(
	ItemStatID int NOT NULL IDENTITY (1, 1),
	ItemID int NOT NULL,
	StatType nvarchar(50) NOT NULL,
	Rank int NULL,
	DiceCount int NULL,
	DiceReroll int NULL,
	DiceColor nvarchar(50) NULL,
	ArmorPenetration int NULL,
	Special nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ItemStat ADD CONSTRAINT
	PK_ItemStat PRIMARY KEY CLUSTERED 
	(
	ItemStatID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ItemStat SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE ItemStat
ADD CONSTRAINT FK_ItemStat
FOREIGN KEY (ItemID)
REFERENCES Item(ItemID)

COMMIT
