BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ItemSetMapping
	(
	ItemSetMappingID int NOT NULL IDENTITY (1, 1),
	ItemID int NOT NULL,
	ItemSetID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ItemSetMapping ADD CONSTRAINT
	PK_ItemSetMapping PRIMARY KEY CLUSTERED 
	(
	ItemSetMappingID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ItemSetMapping SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE ItemSetMapping
ADD CONSTRAINT FK_Item
FOREIGN KEY (ItemID)
REFERENCES Item(ItemID)

ALTER TABLE ItemSetMapping
ADD CONSTRAINT FK_ItemSetMapping
FOREIGN KEY (ItemSetID)
REFERENCES ItemSet(ItemSetID)

COMMIT
