BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Entrance
	(
	EntranceID int NOT NULL IDENTITY (1, 1),
	SectorID int NOT NULL,
	Name nvarchar(50) NOT NULL,
	Cell1X int NOT NULL,
	Cell1Y int NOT NULL,
	Cell2X int NOT NULL,
	Cell2Y int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Entrance ADD CONSTRAINT
	PK_Entrance PRIMARY KEY CLUSTERED 
	(
	EntranceID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Entrance SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE Entrance
ADD CONSTRAINT FK_SectorEntrance
FOREIGN KEY (SectorID)
REFERENCES Sector(SectorID)

COMMIT
