BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ItemSet
	(
	ItemSetID int NOT NULL IDENTITY (1, 1),
	Name nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ItemSet ADD CONSTRAINT
	PK_ItemSet PRIMARY KEY CLUSTERED 
	(
	ItemSetID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ItemSet SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE Item
ADD CONSTRAINT FK_ItemSetRequired
FOREIGN KEY (ItemSetRequired)
REFERENCES ItemSet(ItemSetID)

COMMIT
