BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.DefenseSet
	(
	DefenseSetID int NOT NULL IDENTITY (1, 1),
	Name nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.DefenseSet ADD CONSTRAINT
	PK_DefenseSet PRIMARY KEY CLUSTERED 
	(
	DefenseSetID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.DefenseSet SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE Unit
ADD CONSTRAINT FK_DefenseSet
FOREIGN KEY (DefenseSetID)
REFERENCES DefenseSet(DefenseSetID)

ALTER TABLE DefenseRoll
ADD CONSTRAINT FK_DefenseSetDefenseRoll
FOREIGN KEY (DefenseSetID)
REFERENCES DefenseSet(DefenseSetID)

COMMIT
