SET IDENTITY_INSERT Mission ON

INSERT INTO Mission (MissionID, MissionNumber, Name, TextBriefing, TextDescription, TextTimeLimit, TextDarkLegion, TextRewards, Difficulty, IsSecondaryMissions, ImgMissionPath, ImgMapPath,
					 RewardDoomtrooperCredits, RewardDoomtrooperPromotionPoints, RewardDoomtrooperItemID, RewardLegionCredits, RewardLegionPromotionPoints, RewardLegionItemID)
             VALUES (1, 1, 'Eagle Strike', --mission number, name
'The entrance by Alakhai''s Citadel has been blown open by the bomb squad. Doomtrooper entrance points are marked.',
'The doomtroopers must eliminate 20 Promotion Points of Dark Legion creatures. By the end of the mission, one Doomtrooper form a player''s team must exit the gameboard from sector 1 or 4 to collect the reward. Secondary Mission Cards are not used',
'4 Rounds (Reminder, Dark Legion Player draws 4 Event Cards). Reinforcements on the Event Cards enter at entrance points in the Citadel marked.',
'Force Cards 1-7 (Reminder: Dark Legion Player places the Force Cards on the gameboard sectors.)',
'Doomtroopers receive 1 Credit. If the Doomtroopers fail to complete the mission, the Dark Legion player receives 2 Credits.',
			        1, 0,	--difficulty, secondaryMissions
			        null, null, --mission img, map img
			        1, 0, null, --doomtrooper rewards
			        2, 0, null) --legion rewards
INSERT INTO Objective (MissionID,               Type,          Name,                                           Description, TimeLimitRound, TimeLimitIsStartOfRound, RequiredCount1, RequiredCount2, RequiredCount3, RequiredUnitType1, RequiredUnitType2, RequiredUnitType3, RequiredSectorID1, RequiredSectorID2, RequiredSectorID3, RequiredSectorID4, RequiredCellX, RequiredCellY, Special1, Special2, Special3)
               VALUES (        1, 'Promotion Points', 'Elimination', 'Wipe out 20 promotion points worth of legion forces',           null,                    null,             20,           null,           null,              null,              null,              null,              null,              null,              null,              null,          null,          null,     null,     null,     null)
INSERT INTO Objective (MissionID,       Type,     Name,                                                                                            Description, TimeLimitRound, TimeLimitIsStartOfRound, RequiredCount1, RequiredCount2, RequiredCount3, RequiredUnitType1, RequiredUnitType2, RequiredUnitType3, RequiredSectorID1, RequiredSectorID2, RequiredSectorID3, RequiredSectorID4,  RequiredCellX, RequiredCellY, Special1, Special2, Special3)
               VALUES (        1, 'Movement', 'Escape', 'Exit the board from one of the places you were allowed to enter with at least 1 of your doomtroopers',           null,                    null,              1,           null,           null,     'Doomtrooper',              null,              null,                 1,                 4,              null,              null,           null,          null,     null,     null,     null)
INSERT INTO SectorMap (MissionID, SectorID, LocationX, LocationY, IsEntranceTBlocked, IsEntranceTForDoomtroopers, IsEntranceTForLegion, IsEntranceRBlocked, IsEntranceRForDoomtroopers, IsEntranceRForLegion, IsEntranceBBlocked, IsEntranceBForDoomtroopers, IsEntranceBForLegion, IsEntranceLBlocked, IsEntranceLForDoomtroopers, IsEntranceLForLegion)
               VALUES (        1,        1,         0,         0,                  0,                          1,                    0,                  1,                          0,                    0,                  1,                          0,                    0,                  0,                          1,                    0)
INSERT INTO SectorMap (MissionID, SectorID, LocationX, LocationY, IsEntranceTBlocked, IsEntranceTForDoomtroopers, IsEntranceTForLegion, IsEntranceRBlocked, IsEntranceRForDoomtroopers, IsEntranceRForLegion, IsEntranceBBlocked, IsEntranceBForDoomtroopers, IsEntranceBForLegion, IsEntranceLBlocked, IsEntranceLForDoomtroopers, IsEntranceLForLegion)
               VALUES (        1,        4,         0,         1,                  1,                          0,                    0,                  0,                          1,                    0,                  0,                          1,                    0,                  0,                          1,                    0)
INSERT INTO SectorMap (MissionID, SectorID, LocationX, LocationY, IsEntranceTBlocked, IsEntranceTForDoomtroopers, IsEntranceTForLegion, IsEntranceRBlocked, IsEntranceRForDoomtroopers, IsEntranceRForLegion, IsEntranceBBlocked, IsEntranceBForDoomtroopers, IsEntranceBForLegion, IsEntranceLBlocked, IsEntranceLForDoomtroopers, IsEntranceLForLegion)
               VALUES (        1,        2,         1,         0,                  0,                          0,                    1,                  1,                          0,                    0,                  0,                          0,                    1,                  1,                          0,                    0)
INSERT INTO SectorMap (MissionID, SectorID, LocationX, LocationY, IsEntranceTBlocked, IsEntranceTForDoomtroopers, IsEntranceTForLegion, IsEntranceRBlocked, IsEntranceRForDoomtroopers, IsEntranceRForLegion, IsEntranceBBlocked, IsEntranceBForDoomtroopers, IsEntranceBForLegion, IsEntranceLBlocked, IsEntranceLForDoomtroopers, IsEntranceLForLegion)
               VALUES (        1,        5,         2,         0,                  0,                          0,                    1,                  0,                          0,                    1,                  0,                          0,                    1,                  1,                          0,                    0)

SET IDENTITY_INSERT Mission OFF