SET IDENTITY_INSERT Unit ON

--BAUHAUS
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     1, 'Steiner', 'Doomtrooper',             1,   'Ranged',          1,            2,             5,              2,                     3,                1,                   0,                     1, 'doomtroopers/Figure-Steiner.png',          null, 'doomtroopers/Icon-Steiner.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     2, 'Valerie', 'Doomtrooper',             1,     'Both',          1,            2,             5,              2,                     3,                3,                   0,                     1, 'doomtroopers/Figure-Valerie.png',          null, 'doomtroopers/Icon-Valerie.jpg',             null)
--MISHIMA
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     3, 'Yojimbo', 'Doomtrooper',             4,    'Melee',          1,            2,             5,              2,                     4,                2,                   0,                     1, 'doomtroopers/Figure-Yojimbo.png',          null, 'doomtroopers/Icon-Yojimbo.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     4,   'Tatsu', 'Doomtrooper',             4,     'Both',          1,            2,             5,              2,                     4,                3,                   0,                     1,   'doomtroopers/Figure-Tatsu.png',          null,   'doomtroopers/Icon-Tatsu.jpg',             null)
--CAPITOL
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     5,  'Hunter', 'Doomtrooper',             3,     'Both',          1,            2,             5,              2,                     3,                3,                   0,                     1,  'doomtroopers/Figure-Hunter.png',          null,  'doomtroopers/Icon-Hunter.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     6, 'Big Bob', 'Doomtrooper',             3,   'Ranged',          1,            2,             5,              2,                     3,                1,                   0,                     1,  'doomtroopers/Figure-BigBob.png',          null,  'doomtroopers/Icon-BigBob.jpg',             null)
--IMPERIAL
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     7, 'Murdoch', 'Doomtrooper',             2,   'Ranged',          1,            2,             5,              2,                     3,                1,                   0,                     1, 'doomtroopers/Figure-Murdoch.png',          null, 'doomtroopers/Icon-Murdoch.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     8, 'Gallagher', 'Doomtrooper',           2,    'Melee',          1,            2,             5,              2,                     3,                2,                   0,                     1, 'doomtroopers/Figure-Gallagher.png',          null, 'doomtroopers/Icon-Gallagher.jpg',             null)
--CYBERTRONIC
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (     9, 'Coral Beach', 'Doomtrooper',         5,     'Both',          1,            3,             5,              2,                     3,                3,                   0,                     1, 'doomtroopers/Figure-CoralBeach.png',          null, 'doomtroopers/Icon-CoralBeach.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (    10, 'Attila III', 'Doomtrooper',          5,   'Ranged',          1,            3,             5,              2,                     3,                1,                   0,                     1, 'doomtroopers/Figure-AttilaIII.png',          null, 'doomtroopers/Icon-AttilaIII.jpg',             null)
--BROTHERHOOD
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (    11, 'Nicodemus', 'Doomtrooper',           6,    'Melee',          1,            2,             5,              2,                     3,                2,                   0,                     1, 'doomtroopers/Figure-Nicodemus.png',          null, 'doomtroopers/Icon-Nicodemus.jpg',             null)
INSERT INTO Unit (UnitID,      Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                     ImgFigurePath, ImgPosterPath,                     ImgIconPath, ImgAlternatePath)
          VALUES (    12, 'Crenshaw', 'Doomtrooper',            6,   'Ranged',          1,            2,             5,              2,                     3,                1,                   0,                     1, 'doomtroopers/Figure-Crenshaw.png',          null, 'doomtroopers/Icon-Crenshaw.jpg',             null)
--LEGION
INSERT INTO Unit (UnitID,          Name,          Type, CorporationID, CombatType, ArmorSetID, DefenseSetID, DefaultHealth, DefaultActions, DefaultStepsPerAction, DefaultItemSetID, KillPromotionPoints, DamagePromotionPoints,                   ImgFigurePath, ImgPosterPath,                   ImgIconPath, ImgAlternatePath)
          VALUES (    19, 'Legionnaire', 'Legionnaire',            10,     'Both',          2,            1,             1,              2,                     3,                4,                   1,                     0, 'legion/Figure-Legionnaire.png',          null, 'legion/Icon-Legionnaire.png',             null)

SET IDENTITY_INSERT Unit OFF