SET IDENTITY_INSERT ArmorSet ON

INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (1, 'Battle Armor')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 1, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 2, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 3, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 4, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 5, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (1, 6, 1)

INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (2, 'Light Armor')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 1, 0)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 2, 0)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 3, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 4, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 5, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (2, 6, 1)
		   
INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (3, 'Necro Fusion Armor')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 1, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 2, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 3, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 4, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 5, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (3, 6, 2)
		   
INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (4, 'Officer''s Gear')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 1, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 2, 1)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 3, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 4, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 5, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (4, 6, 2)
		   		   
INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (5, 'Battleplate')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 1, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 2, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 3, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 4, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 5, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (5, 6, 3)
		   		   
INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (6, 'Necro Priest Robe')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 1, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 2, 2)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 3, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 4, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 5, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (6, 6, 3)
		   		   
INSERT INTO ArmorSet (ArmorSetID, Name) VALUES (7, 'Wargear')
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 1, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 2, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 3, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 4, 3)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 5, 4)
INSERT INTO Armor (ArmorSetID, Rank, DamageReduction) VALUES (7, 6, 4)

SET IDENTITY_INSERT ArmorSet OFF